import "./globals.css";
import Layout from "@/shared/layout/Layout";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl">
        <body className="bg-white font-estedad">
        <Layout>
            {children}
        </Layout>
        </body>
        </html>
    );
}
